replicaCount: 1

image:
  repository: ghcr.io/codbex/codbex-athena
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  ingressClassName: nginx
  hosts:
    - host: dev.athena.eu1.codbex.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - dev.athena.eu1.codbex.com
      secretName: codbex-athena-tls-secret

resources:
  requests:
    memory: "1Gi"
    cpu: "0.5"
  limits:
    memory: "4Gi"
    cpu: "2"
