name: Build and Test

on:
    pull_request:
        branches: [main]
    push:
        branches: [main]

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Build codbex-athena Docker image from source
              run: |
                  docker build -t codbex-athena:test application/

            - name: Build codbex-athena-data-sample Docker image from source
              run: |
                  docker build -t codbex-athena-data-sample:test application-data-sample/

            - name: Set APP_IMAGE and APP_DATA_SAMPLE_IMAGE to local builds
              run: |
                  echo "APP_IMAGE=codbex-athena:test" >> $GITHUB_ENV
                  echo "APP_DATA_SAMPLE_IMAGE=codbex-athena-data-sample:test" >> $GITHUB_ENV

            - name: Cache local Maven repository
              uses: actions/cache@v4
              with:
                  path: ~/.m2/repository
                  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: ${{ runner.os }}-maven-

            - name: Set up JDK Corretto 21
              uses: actions/setup-java@v4
              with:
                  distribution: 'corretto'
                  java-version: 21

            - name: Build and test with Maven
              run: mvn clean verify
