name: Deploy to Kubernetes

on:
  workflow_call:
    inputs:
      application-version:
        type: string
        default: latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Create .kube directory
        run: mkdir -p $HOME/.kube

      - name: Authenticate with Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl scale deployments/codbex-athena --replicas=0 -n prod
          kubectl set image deployment/codbex-athena codbex-athena=ghcr.io/codbex/codbex-athena-data-sample:${{ inputs.application-version }} -n prod
          kubectl scale deployments/codbex-athena --replicas=1 -n prod
