name: Pull Request - Application

on:
  pull_request:
    branches:
      - main

jobs:
  application:
    uses: codbex/codbex-infra/.github/workflows/application-pull-request.yaml@feat/add-it-workflows
    with:
      application-name: codbex-athena
      install-dependencies: true
      dockerfile-location: application/
      run-tests: true
      sample-data-folder: application-data-sample/
      build-sample-data: true
    secrets: inherit